name: qcp-1D
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.2
  - scipy=1.11.4
  - matplotlib=3.8.2
  - cython=3.0.7
  - physics-tenpy=0.10.0
  - setuptools>=30.3.0
  - qutip=4.7.3
  - tqdm=4.66.1
  - ruff=0.1.9
  - yapf=0.40.1